Added VPN Tunnel Phase 1/2 Lifetimes
cloudposse/terraform-aws-vpn-connection pull request #55
Opened 2024-10-16 20:00 UTC by jpschafer

## what

Added Tunnel 1/2 Phase 1/2 Lifetime Variables

## why

So I can add custom lifetimes outside of the defaults for customers who have different lifetimes set for their end of the tunnel.

## references

#54 

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpn_connection#tunnel1_phase1_lifetime_seconds

The only issue to note is that in the AWS Console,  you will see 28800 and 3600 respectively instead of "default" for each. I wasn't sure If that really matters but it's the only issue I could think of. I'm open to suggestions on preferences regarding this variable that is technically optional. I wasn't sure if setting it to null would create the same behavior.

2024-10-17 10:41 UTC, gberenice commented
/terratest

2024-10-17 11:29 UTC, gberenice requested changes
@jpschafer could you please fix the variable usage as suggested and run `fmt`?

2024-10-17 11:29 UTC, gberenice commented on main.tf
> +  tunnel2_phase2_lifetime_seconds      = var.vpn_connection_tunnel1_phase2_lifetime_seconds
```suggestion
  tunnel2_phase1_lifetime_seconds      = var.vpn_connection_tunnel2_phase1_lifetime_seconds 
  tunnel2_phase2_lifetime_seconds      = var.vpn_connection_tunnel2_phase2_lifetime_seconds 
```

2024-10-17 15:57 UTC, jpschafer commented on main.tf
> +  tunnel2_phase2_lifetime_seconds      = var.vpn_connection_tunnel1_phase2_lifetime_seconds
Sorry about that, It's corrected.

2024-10-17 16:04 UTC, gberenice commented
/terratest

2024-10-17 19:59 UTC, gberenice approved these changes
Thanks @jpschafer!

2024-10-17 19:59 UTC, merged

2024-10-18 12:00 UTC, jpschafer commented
@gberenice Just wanted to say thank you for helping me out in merging this and letting me contribute to this project. You all do great work! :)