upgrade aws provider
cloudposse/terraform-aws-vpn-connection pull request #8
Opened 2020-12-06 00:48 UTC by AlyRagab

- Upgrading the aws provider version to be "~> 3.0" because the current "2.0" does not work if we have another resources depend on version 3.0

- Error : 

Initializing provider plugins...
- terraform.io/builtin/terraform is built in to Terraform
- Finding hashicorp/null versions matching "~> 2.0"...
- Finding hashicorp/aws versions matching "~> 3.0, ~> 2.0"...
- Using hashicorp/null v2.1.2 from the shared cache directory

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider hashicorp/aws:
no available releases match the given constraints ~> 3.0, ~> 2.0

2020-12-06 01:07 UTC, joe-niland commented
Hi @AlyRagab 
We are using lower bound pinning going forward.

Could you please adjust this for Terraform and for the providers?

2020-12-06 01:17 UTC, joe-niland commented
Here's an example https://github.com/cloudposse/terraform-aws-codebuild/pull/70

2020-12-06 02:27 UTC, aknysh commented on versions.tf
>    required_version = ">= 0.12.0, < 0.14.0"
```suggestion
  required_version = ">= 0.12.0"
```

2020-12-06 02:28 UTC, aknysh commented on versions.tf
> +    aws  = "~> 3.0"
```suggestion
    aws  = ">= 2.0"
```

2020-12-06 02:28 UTC, aknysh commented on versions.tf
>      null = "~> 2.0"
```suggestion
    null = "=> 2.0"
```

2020-12-06 02:29 UTC, aknysh reviewed
thanks @AlyRagab , please see comments.
Please also run the following commands from the repo root:

```
make init
make github/init
make readme
```

2020-12-06 03:12 UTC, AlyRagab commented
Thanks @aknysh for your comments

2020-12-06 03:57 UTC, aknysh commented
/test all

2020-12-06 04:02 UTC, aknysh requested changes
@AlyRagab 
Sorry, but we also need to update the test to use `Go` modules.
Can you please run these commands:

```
make init
make github/init
cd test/src/
go mod init github.com/cloudposse/$(cd ../../ && basename `pwd`)
go mod tidy
git rm Gopkg.*
git add go.*
```

Thanks a lot for your contribution.

2020-12-06 04:02 UTC, aknysh commented
/rebuild-readme

2020-12-06 04:04 UTC, aknysh commented
/test all

2020-12-06 08:47 UTC, joe-niland commented
/test all

2020-12-08 05:12 UTC, AlyRagab commented
/rebuild-readme

2020-12-08 05:12 UTC, AlyRagab commented
/test all

2020-12-08 05:34 UTC, AlyRagab commented
/test all

2020-12-22 03:44 UTC, closed without merging